// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

import { Asset, Entry } from 'contentful'

export interface IContentFields {
  /** title */
  title: string

  /** slug */
  slug?: string | undefined

  /** type */
  type: 'event' | 'gallery' | 'music' | 'news' | 'page' | 'production'

  /** summary */
  summary: string

  /** story */
  story?: string | undefined

  /** link */
  link?: string | undefined

  /** related */
  related?: IContent[] | undefined

  /** media */
  media?: Asset[] | undefined

  /** location */
  location?: { lat: number; lon: number } | undefined
}

/** Content for website. Can be a page, a list item etc. */

export interface IContent extends Entry<IContentFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: 'content'
        linkType: 'ContentType'
        type: 'Link'
      }
    }
  }
}

export type CONTENT_TYPE = 'content'

export type LOCALE_CODE = 'en-GB'

export type CONTENTFUL_DEFAULT_LOCALE_CODE = 'en-GB'
